(setq flycheck-clang-include-path '("."))
(setq flycheck-clang-language-standard nil)
(require 'flycheck)
(add-hook 'after-init-hook #'global-flycheck-mode)
(global-set-key (kbd "M-n") 'flycheck-next-error)
